version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: emerDev
      POSTGRES_PASSWORD: 180281
      POSTGRES_DB: crudGolang
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
