version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672" 
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: seudb
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: seuemail@email.com.br
      PGADMIN_DEFAULT_PASSWORD: mudar123
    ports:
      - "5050:80"
    depends_on:
      - postgresql

volumes:
  rabbitmq_data:
  postgresql_data:
