version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672" 
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: seubd
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: seunome@seumail.com
      PGADMIN_DEFAULT_PASSWORD: mudar123
    ports:
      - "5050:80"
    depends_on:
      - postgresql

  app:
    build: 
      context: .
      dockerfile: Dockerfile 
    image: crud-golang-rabbitmq
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
      - postgresql
    environment:
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: seubd
      POSTGRES_HOST: postgresql  
      POSTGRES_PORT: 5432
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_HOST: rabbitmq  
      RABBITMQ_PORT: 5672

volumes:
  rabbitmq_data:
  postgresql_data:
